# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-10 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeehtmlapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedata',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='employeedata',
            old_name='location',
            new_name='location1',
        ),
        migrations.RenameField(
            model_name='employeedata',
            old_name='mobile',
            new_name='mobile1',
        ),
        migrations.RenameField(
            model_name='employeedata',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='employeedata',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='employeedata',
            old_name='username',
            new_name='username1',
        ),
    ]
